<div style="margin-left:5em;margin-right:5em;margin-top:5em;margin-bottom:1em;">

<img style="width: 286px; height: 275px;" alt="postneedz"
	src="/content/images/post_needz.jpg" align="left" vspace="3" hspace="3">
Let me tell you a bit about what postneedz will accomplish.&nbsp; An
organization such as a church always has needz.&nbsp; The hope is that
the congregation or surrounding community will have the heart and
initiative to serve those needz.&nbsp; The heart is only part of the
solution.&nbsp; The other part, is communication.&nbsp; Without the
ability to properly communicate needz, an organization may fall short in
volunteers.&nbsp; Postneedz will help facilitate that communication.
<br>
<br>
Here are a few examples of how postneedz can benefit the community:
<br>
<br>
Lets say you are a member of a local community such as a church.&nbsp;
You're washing machine goes out this week and you plan on buying a used
one from someone on craigslist.&nbsp; You don't have a truck, and you
don't feel right asking the sellers to deliver.&nbsp; You consider that
your church may be able to fill the need, but you're not sure who has a
truck, or who to start asking.&nbsp; So you log onto postneedz.com and
post a message to your church.&nbsp; Only members in your church will
see this need.&nbsp; At that point, anyone who has registered as a
member of your church can offer to fill this need.
<br>
<br>
Another way to utilize postneedz is where an organization reaches out to
the surrounding community.&nbsp; Metro United Way is having a fund
raising activity this weekend downtown and will need a few extra
volunteers.&nbsp; They can post this need on postneedz.com and the need
will be viewable to everyone in the local community.
<br>
<br>
Below is a diagram to help understand how this process will work.&nbsp;
Individuals can post needz for their local organization to see.&nbsp; An
organization can post needz for the local community to see.&nbsp; A
local community is called a network.
<br>
<img
	style="width: 555px; height: 329px;" alt="Flow Diagram"
	src="/content/images/network.jpg">
<br>
Currently, postneedz is still in development.&nbsp; We are trying to
circulate the word to get everyone to go to the page and enter their
email address.&nbsp; You won't be spammed!&nbsp; We simply want to see
the interest people have in it.&nbsp; Once the site is close to
completion, I will send an email to all who respond, notifying them of
the launch date.
<br>
<br>
Please go to www.postneedz.com and enter your email address.&nbsp; Also,
pass the word around!
<br>
<br>
<br>
Thanks for your support!
<br>
<br>
Jeremy Patrick
<br>
<br>
</div>
