
<table
	style="text-align: left; width: 100%; height: 100%; margin-left: auto; margin-right: auto;"
	border="0" cellpadding="0" cellspacing="0">
	<tbody>
		<tr>
			<td style="vertical-align: bottom; height: 10px;">
			<table style="text-align: left; width: 100%;" border="0"
				cellpadding="0" cellspacing="0">
				<tbody>
					<tr>
						<td style="text-align: right; vertical-align: top; width: 30%"><img
							style="width: 286px; height: 275px;" alt="postneedz"
							src="../content/images/post_needz.jpg" vspace="10"></td>
						<td
							style="text-align: center; vertical-align: top; width: 40%; font-size: 2em;"><br>
						Serving the community<br>
						One need at a time<br>
						<a href="./about/"
							style="font-size: .4em; color: #657383; text-decoration: none;">Learn
						more...</a> </font><br>
						<img style="width: 299px; height: 236px;" alt="volunteer"
							src="../content/images/volunteer.jpg"><br>
						</td>
						<td style="text-align: left; vertical-align: middle; width: 30%">
						<form action="create_account/frm_create_account.php" method="POST">
						<table
							style="text-align: left; 0" cellspacing="0">
							<tbody>
								<tr>
									<td style="vertical-align: top; height: 40px;" colspan="2"><font
										size="+2">Sign up! It's free</font></td>
								</tr>
								<tr>
									<td style="white-space: nowrap; vertical-align: middle;">First
									name:<br>
									</td>
									<td style="vertical-align: top;"><input name="firstname"></td>
								</tr>
								<tr>
									<td style="vertical-align: top;">Last name:</td>
									<td style="vertical-align: top;"><input name="lastname"></td>
								</tr>
								<tr>
									<td style="vertical-align: top;">Email:<br>
									</td>
									<td style="vertical-align: top;"><input name="email"></td>
								</tr>
								<tr>
									<td style="vertical-align: top;">Password:</td>
									<td style="vertical-align: top;"><input name="password"
										type="password"></td>
								</tr>
								<tr>
									<td style="padding-top: .5em;" colspan="2"><input
										value="Submit" type="submit"></td>
								</tr>
							</tbody>
						</table>
						</form>
						</td>
					</tr>
				</tbody>
			</table>
			</td>
		</tr>
	</tbody>
</table>
