  
<script language="JavaScript">


<!--

	function silentErrorHandler() {return true;}
	window.onerror=silentErrorHandler;
	//-->
	</script>
	<!-- GC -->
	<!-- LIBS -->
	<script type="text/javascript"
		src="/lib/ext-3.0.0/adapter/ext/ext-base.js"></script>
	<!-- ENDLIBS -->
	<script type="text/javascript" src="/lib/ext-3.0.0/ext-all.js"></script>
	<script type="text/javascript" src="/common/js/frm_email.js"></script>
	<link rel="stylesheet" type="text/css" href="/common/css/forms.css">
	    
	<!-- Tabs Example Files -->
    <link rel="stylesheet" type="text/css" href="tabs.css" />
    <script type="text/javascript" src="tabs.js"></script>

 </script>